name:                servant-persistent-realworld
version:             0.0.0.1
synopsis:            RealWorld backend using Servant and Persistent
description:         Backend implementation of the RealWorld project with Servant and Persistent
homepage:            https://github.com/jkachmar/servant-persistent-realworld
license:             MIT
author:              jkachmar
copyright:           2017 Joe Kachmar
category:            Web

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - aeson                 >= 1.0  && < 1.1
  - base                  >= 4.7  && < 5
  - bytestring            >= 0.10 && < 0.11
  - classy-prelude        >= 1.2  && < 1.3
  - cryptonite            >= 0.21 && < 0.23
  - dotenv                >= 0.3  && < 0.4
  - esqueleto             >= 2.5  && < 2.6
  - fast-logger           >= 2.4  && < 2.5
  - jose                  >= 0.5  && < 0.6
  - katip                 >= 0.3  && < 0.4
  - lens                  >= 4.15 && < 4.16
  - monad-control         >= 1.0  && < 1.1
  - monad-logger          >= 0.3  && < 0.4
  - mtl                   >= 2.2  && < 2.3
  - persistent            >= 2.6  && < 2.7
  - persistent-postgresql >= 2.6  && < 2.7
  - persistent-template   >= 2.5  && < 2.6
  - servant               # version pinned by stack.yaml
  - servant-auth          # version pinned by stack.yaml
  - servant-auth-server   # version pinned by stack.yaml
  - servant-server        # version pinned by stack.yaml
  - transformers          >= 0.5  && < 0.6
  - transformers-base     >= 0.4  && < 0.5
  - time                  >= 1.6  && < 1.7
  - text                  >= 1.2  && < 1.3
  - uuid                  >= 1.3  && < 1.4
  - wai                   >= 3.2  && < 3.3
  - wai-extra             >= 3.0  && < 3.1
  - warp                  >= 3.2  && < 3.3
  - x509                  >= 1.6  && < 1.7
  - x509-store            >= 1.6  && < 1.7

ghc-options:
  - -Wall
  - -Werror

executables:
  app:
    source-dirs:      app
    main:             Main.hs
    ghc-options:      
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N

    dependencies:
      - servant-persistent-realworld

library:
  source-dirs:        src
